// AESKeyDerivationTests.swift
//
// Verifies the Swift port produces byte-for-byte identical output to the
// Java reference implementation. Test vectors generated by
// analysis/verify_aes/test_aes.py (pycryptodome) which itself was verified
// against the Java DigestAES.encrypt + DigestKey.bKey from the decompiled APK.
//
// If any of these fail, the iOS app will produce ciphertexts the scooter
// will reject — DO NOT MERGE A CHANGE THAT BREAKS THESE.

import XCTest
@testable import SOFLOWCore

final class AESKeyDerivationTests: XCTestCase {

    func testKeyHex() {
        XCTAssertEqual(
            AESKeyDerivation.masterKey.hexUppercase(),
            "30572F52364B3F473050415811632D2B"
        )
        XCTAssertEqual(AESKeyDerivation.masterKey.count, 16)
    }

    func testTV1_zeroBlock() throws {
        let cipher = try DigestAES.encrypt(
            Data(repeating: 0, count: 16),
            key: AESKeyDerivation.masterKey
        )
        XCTAssertEqual(cipher, "F3F06525120E9D152FF1A05872EBBAA1")
    }

    func testTV2_aaaBlock() throws {
        let cipher = try DigestAES.encrypt(
            Data(repeating: 0xAA, count: 16),
            key: AESKeyDerivation.masterKey
        )
        XCTAssertEqual(cipher, "A34F6025B3980B44D2A3A2BDF213670E")
    }

    func testTV3_battery_lock_setting_style() throws {
        // Mirror BleDataOperateManage.battery_lock_setting:
        //   parser = "D706D50000010A"  (cmd D706D5, sub 00, payload 0001, checksum 0A)
        //   pad to 32 hex chars
        //   encrypt with bKey
        let cipher = try AESKeyDerivation.encryptParser("D706D50000010A", padLength: 32)
        XCTAssertEqual(cipher, "8777154CD1667F2D6A78EA4B50DF2B2B")
    }

    func testTV4_change_BleName_style() throws {
        // change_BleName: pad to 64 chars / 32 bytes / 2 AES blocks
        let cipher = try AESKeyDerivation.encryptParser("48424F592D5054", padLength: 64)
        XCTAssertEqual(
            cipher,
            "44DC850085782EADF3BBE4F2F2707190F3F06525120E9D152FF1A05872EBBAA1"
        )
    }

    func testTV5_DTSwitchParser_style() throws {
        // DTSwitchParser: pad to 128 chars / 64 bytes / 4 AES blocks
        let cipher = try AESKeyDerivation.encryptParser(
            "11111111111111111111111111111111", padLength: 128)
        XCTAssertEqual(
            cipher,
            "5C7323CE362702B924E087D080A1C40A" +
            "F3F06525120E9D152FF1A05872EBBAA1" +
            "F3F06525120E9D152FF1A05872EBBAA1" +
            "F3F06525120E9D152FF1A05872EBBAA1"
        )
    }

    func testRoundTrip() throws {
        let plainHex = "D706D50000010A000000000000000000"
        let plain = Data(hexString: plainHex)!
        let cipher = try DigestAES.encrypt(plain, key: AESKeyDerivation.masterKey)
        let back = try AESKeyDerivation.decryptToHex(cipher)
        XCTAssertEqual(back, plainHex)
    }

    func testPadRightWithZeros() {
        XCTAssertEqual(AESKeyDerivation.padRightWithZeros("AB", to: 8), "AB000000")
        XCTAssertEqual(AESKeyDerivation.padRightWithZeros("ABCDEFGH", to: 8), "ABCDEFGH")
        XCTAssertEqual(AESKeyDerivation.padRightWithZeros("ABCDEFGHI", to: 8), "ABCDEFGHI")
    }
}

extension Data {
    fileprivate func hexUppercase() -> String {
        return self.map { String(format: "%02X", $0) }.joined()
    }
}
